#=================== Initial Configs ===============#
include:
  - template: SAST.gitlab-ci.yml
  - template: Security/License-Scanning.gitlab-ci.yml
  - template: Security/Secret-Detection.gitlab-ci.yml
  - template: Dependency-Scanning.gitlab-ci.yml
  - template: Code-Quality.gitlab-ci.yml

stages:
  - build
  - test
  - deploy

variables:
  DS_DEFAULT_ANALYZERS: "retire.js"
  SAST_DEFAULT_ANALYZERS: "eslint"

#=================== BUILD - Package ===============#
build_package:
    image: node:latest
    stage: build
    rules:
      - if: '$CI_COMMIT_BRANCH == "develop"'    
      - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      - if: '$CI_COMMIT_TAG == /^v.*$/'
        when: never
      - if: $CI_COMMIT_TAG
    cache:
      paths:
      - node_modules/
    script:
      - npm install --unsafe-perm -g vsce
      - npm install --unsafe-perm
      - vsce package -o $CI_PROJECT_NAME-$CI_JOB_ID-$CI_PIPELINE_SOURCE.vsix --baseContentUrl $CI_PROJECT_URL/blob/$CI_COMMIT_REF_NAME
    artifacts:
      name: "artifacts-$CI_PROJECT_NAME-$CI_JOB_ID"
      expire_in: 2 weeks
      paths:
        - "*.vsix"

build_package_release:
    image: node:latest
    stage: build
    rules:
     - if: '$CI_COMMIT_TAG == /^v.*$/'
    cache:
      paths:
      - node_modules/
    script:
      - npm install --unsafe-perm -g vsce
      - npm install --unsafe-perm
      - vsce package -o $CI_PROJECT_NAME-$CI_COMMIT_TAG.vsix --baseContentUrl $BASE_CONTENT_URL
    artifacts:
      name: "artifacts-$CI_PROJECT_NAME-$CI_COMMIT_TAG"
      paths:
        - "*.vsix"


#=================== DEPLOY - Package ==============#
deploy_package:
    image: node:latest
    stage: deploy
    rules:
     - if: '$CI_COMMIT_TAG == /^v.*$/'
    variables:
      GIT_STRATEGY: none
    script:
      - npm install --unsafe-perm -g vsce
      - vsce publish -p $VSCE_PERSONAL_ACCESS_TOKEN --packagePath $CI_PROJECT_NAME-$CI_COMMIT_TAG.vsix

#=================== TEST ==========================#
eslint-sast:
  rules:
    - if: $CI_COMMIT_TAG
    - if: '$CI_COMMIT_BRANCH == "develop"'    
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'

secret_detection:
  rules:
    - if: $CI_COMMIT_TAG
    - if: '$CI_COMMIT_BRANCH == "develop"'    
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'

license_scanning:
  rules:
    - if: $CI_COMMIT_TAG
    - if: '$CI_COMMIT_BRANCH == "develop"'    
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
    - if: '$CI_PIPELINE_SOURCE == "schedule"'
  variables:
    NODE_ENV: production

retire-js-dependency_scanning:
  rules:
    - if: $CI_COMMIT_TAG
    - if: '$CI_COMMIT_BRANCH == "develop"'    
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
    - if: '$CI_PIPELINE_SOURCE == "schedule"'

code_quality:
  rules:
    - if: $CI_COMMIT_TAG
    - if: '$CI_COMMIT_BRANCH == "develop"'    
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
